# Generated by Django 4.2.4 on 2023-11-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet',
            new_name='name',
        ),
    ]
